export const tasks = [
  {
    id: 1,
    title: 'Load dishwasher',
    containerID: 'green',
    dateCreated: '01/01/22',
    lastSorted: '01/01/22',
    lastCompleted: '01/01/22',
    trackCompletion: true,
    recurring: true,
  },
  {
    id: 2,
    title: 'Clean doormat',
    containerID: 'green',
    dateCreated: '02/01/22',
    lastSorted: '02/01/22',
    lastCompleted: '02/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 3,
    title: 'Water plants',
    containerID: 'green',
    dateCreated: '03/01/22',
    lastSorted: '03/01/22',
    lastCompleted: '03/01/22',
    trackCompletion: true,
    recurring: true,
  },
  {
    id: 4,
    title: 'Take out trash',
    containerID: 'orange',
    dateCreated: '04/01/22',
    lastSorted: '04/01/22',
    lastCompleted: '04/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 5,
    title: 'Walk the dog',
    containerID: 'orange',
    dateCreated: '05/01/22',
    lastSorted: '05/01/22',
    lastCompleted: '05/01/22',
    trackCompletion: true,
    recurring: true,
  },
  {
    id: 6,
    title: 'Do laundry',
    containerID: 'orange',
    dateCreated: '06/01/22',
    lastSorted: '06/01/22',
    lastCompleted: '06/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 7,
    title: 'Vacuum the floor',
    containerID: 'orange',
    dateCreated: '07/01/22',
    lastSorted: '07/01/22',
    lastCompleted: '07/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 8,
    title: 'Mow the lawn',
    containerID: 'yellow',
    dateCreated: '08/01/22',
    lastSorted: '08/01/22',
    lastCompleted: '08/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 9,
    title: 'Wash dishes',
    containerID: 'yellow',
    dateCreated: '09/01/22',
    lastSorted: '09/01/22',
    lastCompleted: '09/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 10,
    title: 'Sweep the floor',
    containerID: 'done',
    dateCreated: '10/01/22',
    lastSorted: '10/01/22',
    lastCompleted: '10/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 11,
    title: 'Clean windows',
    containerID: 'green',
    dateCreated: '11/01/22',
    lastSorted: '11/01/22',
    lastCompleted: '11/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 12,
    title: 'Organize closet',
    containerID: 'green',
    dateCreated: '12/01/22',
    lastSorted: '12/01/22',
    lastCompleted: '12/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 13,
    title: 'Dust furniture',
    containerID: 'green',
    dateCreated: '13/01/22',
    lastSorted: '13/01/22',
    lastCompleted: '13/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 14,
    title: 'Wash car',
    containerID: 'green',
    dateCreated: '14/01/22',
    lastSorted: '14/01/22',
    lastCompleted: '14/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 15,
    title: 'Clean bathroom',
    containerID: 'done',
    dateCreated: '15/01/22',
    lastSorted: '15/01/22',
    lastCompleted: '15/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 16,
    title: 'Wipe countertops',
    containerID: 'done',
    dateCreated: '16/01/22',
    lastSorted: '16/01/22',
    lastCompleted: '16/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 17,
    title: 'Dust blinds',
    containerID: 'done',
    dateCreated: '17/01/22',
    lastSorted: '17/01/22',
    lastCompleted: '17/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 18,
    title: 'Clean refrigerator',
    containerID: 'done',
    dateCreated: '18/01/22',
    lastSorted: '18/01/22',
    lastCompleted: '18/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 19,
    title: 'Wash windows',
    containerID: 'done',
    dateCreated: '19/01/22',
    lastSorted: '19/01/22',
    lastCompleted: '19/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 20,
    title: 'Dust shelves',
    containerID: 'done',
    dateCreated: '20/01/22',
    lastSorted: '20/01/22',
    lastCompleted: '20/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 21,
    title: 'Organize desk',
    containerID: 'recent',
    dateCreated: '21/01/22',
    lastSorted: '21/01/22',
    lastCompleted: '21/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 22,
    title: 'Clean oven',
    containerID: 'recent',
    dateCreated: '22/01/22',
    lastSorted: '22/01/22',
    lastCompleted: '22/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 23,
    title: 'Wash bedding',
    containerID: 'recent',
    dateCreated: '23/01/22',
    lastSorted: '23/01/22',
    lastCompleted: '23/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 24,
    title: 'Sweep porch',
    containerID: 'recent',
    dateCreated: '24/01/22',
    lastSorted: '24/01/22',
    lastCompleted: '24/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 25,
    title: 'Clean microwave',
    containerID: 'recent',
    dateCreated: '25/01/22',
    lastSorted: '25/01/22',
    lastCompleted: '25/01/22',
    trackCompletion: true,
    recurring: false,
  },
  {
    id: 26,
    title: 'Wipe mirrors',
    containerID: 'recent',
    dateCreated: '26/01/22',
    lastSorted: '26/01/22',
    lastCompleted: '26/01/22',
    trackCompletion: false,
    recurring: false,
  },
  {
    id: 27,
    title: 'Dust ceiling fans',
    containerID: 'recent',
    dateCreated: '27/01/22',
    lastSorted: '27/01/22',
    lastCompleted: '27/01/22',
    trackCompletion: true,
    recurring: false,
  },
];
